server:
  port: 8080
  servlet:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
spring:
  main:
    allow-bean-definition-overriding: true
  liquibase:
    enabled: false
    change-log: classpath:/db/changelog/changelog-master.xml
    contexts: local
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    database: default
  datasource:
    name: accounting
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://db:5432/se7a
    username: se7a
    password: root
  data:
    web:
      pageable:
        default-page-size: 20
  messages:
    basename: i18n/messages
    encoding: UTF-8
    fallback-to-system-locale: false
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui/index.html
    url: /v3/api-docs
